### ISSUE TITLE
Needs updating

### ISSUE THREAD

**Issue by mrwkbrdr** [UniversalDevicesInc-PG3/udi-rachio-poly#1]
Could you be so kind and work towards updating this node server. I for on and probably most do not want to open ports. I would pay for this node sever if the owner would work with Rachio to provide local connection to the device.

Thank you,

**Comment by jimboca** [comment]
It is not possible to have a local connection, Rachio does not allow direct access to the devices.  Version 5.0.0 will support using the UDI Portal for which will eliminate the need for opening a local port as mentioned in #4.
