### ISSUE TITLE
Could you be so kind and work towards updating this node server. I for on and probably most do not want to open ports. I would pay for this node sever if the owner would work with Rachio to provide local connection to the device.

### ISSUE THREAD

**Issue by mrwkbrdr** [UniversalDevicesInc-PG3/udi-rachio-poly#2]
Could you be so kind and work towards updating this node server. I for on and probably most do not want to open ports. I would pay for this node sever if the owner would work with Rachio to provide local connection to the device.

Thank you,

_Originally posted by @mrwkbrdr in https://github.com/UniversalDevicesInc-PG3/udi-rachio-poly/issues/1_

**Comment by jimboca** [comment]
Same as #1
