### ISSUE TITLE
Is anyone supporting this?

### ISSUE THREAD

**Issue by jimboca** [UniversalDevicesInc-PG3/udi-rachio-poly#3]
I'd like to take it over if nobody is.  Hopefully we can avoid opening a local port using the portal now.
See https://forum.universal-devices.com/topic/43771-status-in-program/#comment-384848

**Comment by bpaauwe** [comment]
I did the port to PG3 and I don't believe the original author picked it up.  So I think it's yours now :)

**Comment by jimboca** [comment]
Thanks @bpaauwe, I also got permission from the previous owner in the thread mentioned above.
Can you open permission for me?
ERROR: Permission to UniversalDevicesInc-PG3/udi-rachio-poly.git denied to jimboca.

**Comment by jimboca** [comment]
I have taken over.
